name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  infra-build:
    runs-on: ubuntu-latest
    name: "infra-build"
    steps:
      - uses: actions/checkout@v2
      - name: build Bicep file
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az bicep build --file ./infra/main.bicep --outfile ./main.json
      - name: Upload the ARM template as a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: ./main.json
          name: arm-template
          if-no-files-found: error
  infra-deploy:
    runs-on: ubuntu-latest
    needs: [infra-build]
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/download-artifact@v2
        with:
          name: arm-template
      - name: Deploy bicep to Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment sub create --name akslab --location westeurope --template-file ./main.json
